Add ability to disable media mixing and recording Fix incorrect disabling of plugin when LIDs disabled Disable extra files when H.501, H.450 and H.460 are disabled

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -744,12 +744,14 @@ OPAL_H450
 OPAL_H460
 OPAL_H239
 OPAL_H501
+OPAL_T120DATA
 OPAL_LID
 OPAL_IVR
 OPAL_RFC4175
 OPAL_AEC
 OPAL_G711PLC
 OPAL_STATISTICS
+OPAL_HAS_MIXER
 OPAL_PLUGINS
 subdirs
 OPAL_SAMPLES
@@ -1386,6 +1388,7 @@ Optional Features:
   --enable-h460           whether to enable H.460
   --enable-h239           whether to enable H.239
   --enable-h501           whether to enable H.501
+  --enable-t120           whether to enable T.120
   --enable-lid            whether to enable LID support
   --enable-ivr            whether to enable IVR support
   --enable-rfc4175        whether to enable RFC4175 support
@@ -1393,6 +1396,7 @@ Optional Features:
                           support
   --enable-g711plc        whether to enable Packet Loss Concealment for G.711
   --enable-statistics     whether to enable statistics gathering support
+  --enable-mixer          whether to enable media mixing support
   --enable-plugins        whether to enable plugin support
   --enable-samples        whether to enable samples build
 
@@ -4372,6 +4376,7 @@ OPAL_H450=yes
 OPAL_H460=yes
 OPAL_H239=yes
 OPAL_H501=yes
+OPAL_T120DATA=no
 OPAL_LID=yes
 OPAL_STATISTICS=yes
 OPAL_AEC=yes
@@ -4386,6 +4391,7 @@ OPAL_JAVA=yes
 OPAL_HAS_MSRP=yes
 OPAL_HAS_SIPIM=yes
 OPAL_HAS_RFC4103=yes
+OPAL_HAS_MIXER=yes
 PTLIB_REC_VERSION="2.0.0"
 
 
@@ -10656,6 +10662,50 @@ _ACEOF
 
 
 
+          if test "x$OPAL_T120DATA" = "x"; then
+            { { echo "$as_me:$LINENO: error: No default specified for OPAL_T120DATA, please correct configure.ac" >&5
+echo "$as_me: error: No default specified for OPAL_T120DATA, please correct configure.ac" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+          # Check whether --enable-t120 was given.
+if test "${enable_t120+set}" = set; then
+  enableval=$enable_t120; OPAL_T120DATA=$enableval
+fi
+
+
+          if test "xOPAL_H323" != "x"; then
+            if test "x$OPAL_H323" != "xyes"; then
+              { echo "$as_me:$LINENO: t120 support disabled due to disabled dependency OPAL_H323" >&5
+echo "$as_me: t120 support disabled due to disabled dependency OPAL_H323" >&6;}
+	      OPAL_T120DATA=no
+	    fi
+	  fi
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: t120 support disabled due to disabled dependency " >&5
+echo "$as_me: t120 support disabled due to disabled dependency " >&6;}
+	      OPAL_T120DATA=no
+	    fi
+	  fi
+
+
+          { echo "$as_me:$LINENO: checking whether to enable T.120" >&5
+echo $ECHO_N "checking whether to enable T.120... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $OPAL_T120DATA" >&5
+echo "${ECHO_T}$OPAL_T120DATA" >&6; }
+
+
+          if test "x$OPAL_T120DATA" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define OPAL_T120DATA 1
+_ACEOF
+
+          fi
+
+
+
           if test "x$OPAL_LID" = "x"; then
             { { echo "$as_me:$LINENO: error: No default specified for OPAL_LID, please correct configure.ac" >&5
 echo "$as_me: error: No default specified for OPAL_LID, please correct configure.ac" >&2;}
@@ -10914,6 +10964,50 @@ echo "${ECHO_T}$OPAL_STATISTICS" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_STATISTICS 1
+_ACEOF
+
+          fi
+
+
+
+          if test "x$OPAL_HAS_MIXER" = "x"; then
+            { { echo "$as_me:$LINENO: error: No default specified for OPAL_HAS_MIXER, please correct configure.ac" >&5
+echo "$as_me: error: No default specified for OPAL_HAS_MIXER, please correct configure.ac" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+          # Check whether --enable-mixer was given.
+if test "${enable_mixer+set}" = set; then
+  enableval=$enable_mixer; OPAL_HAS_MIXER=$enableval
+fi
+
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: mixer support disabled due to disabled dependency " >&5
+echo "$as_me: mixer support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_MIXER=no
+	    fi
+	  fi
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: mixer support disabled due to disabled dependency " >&5
+echo "$as_me: mixer support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_MIXER=no
+	    fi
+	  fi
+
+
+          { echo "$as_me:$LINENO: checking whether to enable media mixing support" >&5
+echo $ECHO_N "checking whether to enable media mixing support... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $OPAL_HAS_MIXER" >&5
+echo "${ECHO_T}$OPAL_HAS_MIXER" >&6; }
+
+
+          if test "x$OPAL_HAS_MIXER" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define OPAL_HAS_MIXER 1
 _ACEOF
 
           fi
@@ -11847,12 +11941,14 @@ OPAL_H450!$OPAL_H450$ac_delim
 OPAL_H460!$OPAL_H460$ac_delim
 OPAL_H239!$OPAL_H239$ac_delim
 OPAL_H501!$OPAL_H501$ac_delim
+OPAL_T120DATA!$OPAL_T120DATA$ac_delim
 OPAL_LID!$OPAL_LID$ac_delim
 OPAL_IVR!$OPAL_IVR$ac_delim
 OPAL_RFC4175!$OPAL_RFC4175$ac_delim
 OPAL_AEC!$OPAL_AEC$ac_delim
 OPAL_G711PLC!$OPAL_G711PLC$ac_delim
 OPAL_STATISTICS!$OPAL_STATISTICS$ac_delim
+OPAL_HAS_MIXER!$OPAL_HAS_MIXER$ac_delim
 OPAL_PLUGINS!$OPAL_PLUGINS$ac_delim
 subdirs!$subdirs$ac_delim
 OPAL_SAMPLES!$OPAL_SAMPLES$ac_delim
@@ -11874,7 +11970,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 59; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 61; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
