Ensure IM code obeys configure flags

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -735,7 +735,9 @@ OPAL_H323
 OPAL_IAX2
 OPAL_H224FECC
 OPAL_T38_CAPABILITY
-OPAL_IM_CAPABILITY
+OPAL_HAS_MSRP
+OPAL_HAS_SIPIM
+OPAL_HAS_RFC4103
 OPAL_FAX
 OPAL_H450
 OPAL_H460
@@ -1371,7 +1373,9 @@ Optional Features:
   --enable-iax            whether to enable IAX2 protocol support
   --enable-h224           whether to enable H.224 protocol support
   --enable-t38            whether to enable T.38 capability support
-  --enable-im             whether to enable IM capability support
+  --enable-msrp           whether to enable MSRP support
+  --enable-sipim          whether to enable SIPIM session support
+  --enable-rfc4103        whether to enable RFC4103 support
   --enable-fax            whether to enable T.38 FAX protocol support
   --enable-h450           whether to enable H.450
   --enable-h460           whether to enable H.460
@@ -4353,7 +4357,6 @@ OPAL_SIP=yes
 OPAL_IAX2=yes
 OPAL_VIDEO=yes
 OPAL_T38_CAPABILITY=yes
-OPAL_IM_CAPABILITY=yes
 OPAL_FAX=yes
 OPAL_H224FECC=yes
 OPAL_H450=yes
@@ -4370,6 +4373,9 @@ OPAL_SAMPLES=no
 OPAL_ZRTP=no
 OPAL_SHARED_LIB=yes
 OPAL_JAVA=yes
+OPAL_HAS_MSRP=yes
+OPAL_HAS_SIPIM=yes
+OPAL_HAS_RFC4103=yes
 PTLIB_REC_VERSION="2.0.0"
 
 
@@ -9974,44 +9980,132 @@ _ACEOF
 
 
 
-          if test "x$OPAL_IM_CAPABILITY" = "x"; then
-            { { echo "$as_me:$LINENO: error: No default specified for OPAL_IM_CAPABILITY, please correct configure.ac" >&5
-echo "$as_me: error: No default specified for OPAL_IM_CAPABILITY, please correct configure.ac" >&2;}
+          if test "x$OPAL_HAS_MSRP" = "x"; then
+            { { echo "$as_me:$LINENO: error: No default specified for OPAL_HAS_MSRP, please correct configure.ac" >&5
+echo "$as_me: error: No default specified for OPAL_HAS_MSRP, please correct configure.ac" >&2;}
    { (exit 1); exit 1; }; }
 	  fi
-          # Check whether --enable-im was given.
-if test "${enable_im+set}" = set; then
-  enableval=$enable_im; OPAL_IM_CAPABILITY=$enableval
+          # Check whether --enable-msrp was given.
+if test "${enable_msrp+set}" = set; then
+  enableval=$enable_msrp; OPAL_HAS_MSRP=$enableval
 fi
 
 
           if test "x" != "x"; then
             if test "x$" != "xyes"; then
-              { echo "$as_me:$LINENO: im support disabled due to disabled dependency " >&5
-echo "$as_me: im support disabled due to disabled dependency " >&6;}
-	      OPAL_IM_CAPABILITY=no
+              { echo "$as_me:$LINENO: msrp support disabled due to disabled dependency " >&5
+echo "$as_me: msrp support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_MSRP=no
 	    fi
 	  fi
 
           if test "x" != "x"; then
             if test "x$" != "xyes"; then
-              { echo "$as_me:$LINENO: im support disabled due to disabled dependency " >&5
-echo "$as_me: im support disabled due to disabled dependency " >&6;}
-	      OPAL_IM_CAPABILITY=no
+              { echo "$as_me:$LINENO: msrp support disabled due to disabled dependency " >&5
+echo "$as_me: msrp support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_MSRP=no
 	    fi
 	  fi
 
 
-          { echo "$as_me:$LINENO: checking whether to enable IM capability support" >&5
-echo $ECHO_N "checking whether to enable IM capability support... $ECHO_C" >&6; }
-          { echo "$as_me:$LINENO: result: $OPAL_IM_CAPABILITY" >&5
-echo "${ECHO_T}$OPAL_IM_CAPABILITY" >&6; }
+          { echo "$as_me:$LINENO: checking whether to enable MSRP support" >&5
+echo $ECHO_N "checking whether to enable MSRP support... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $OPAL_HAS_MSRP" >&5
+echo "${ECHO_T}$OPAL_HAS_MSRP" >&6; }
 
 
-          if test "x$OPAL_IM_CAPABILITY" = "xyes"; then
+          if test "x$OPAL_HAS_MSRP" = "xyes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define OPAL_IM_CAPABILITY 1
+#define OPAL_HAS_MSRP 1
+_ACEOF
+
+          fi
+
+
+
+          if test "x$OPAL_HAS_SIPIM" = "x"; then
+            { { echo "$as_me:$LINENO: error: No default specified for OPAL_HAS_SIPIM, please correct configure.ac" >&5
+echo "$as_me: error: No default specified for OPAL_HAS_SIPIM, please correct configure.ac" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+          # Check whether --enable-sipim was given.
+if test "${enable_sipim+set}" = set; then
+  enableval=$enable_sipim; OPAL_HAS_SIPIM=$enableval
+fi
+
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: sipim support disabled due to disabled dependency " >&5
+echo "$as_me: sipim support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_SIPIM=no
+	    fi
+	  fi
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: sipim support disabled due to disabled dependency " >&5
+echo "$as_me: sipim support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_SIPIM=no
+	    fi
+	  fi
+
+
+          { echo "$as_me:$LINENO: checking whether to enable SIPIM session support" >&5
+echo $ECHO_N "checking whether to enable SIPIM session support... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $OPAL_HAS_SIPIM" >&5
+echo "${ECHO_T}$OPAL_HAS_SIPIM" >&6; }
+
+
+          if test "x$OPAL_HAS_SIPIM" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define OPAL_HAS_SIPIM 1
+_ACEOF
+
+          fi
+
+
+
+          if test "x$OPAL_HAS_RFC4103" = "x"; then
+            { { echo "$as_me:$LINENO: error: No default specified for OPAL_HAS_RFC4103, please correct configure.ac" >&5
+echo "$as_me: error: No default specified for OPAL_HAS_RFC4103, please correct configure.ac" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+          # Check whether --enable-rfc4103 was given.
+if test "${enable_rfc4103+set}" = set; then
+  enableval=$enable_rfc4103; OPAL_HAS_RFC4103=$enableval
+fi
+
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: rfc4103 support disabled due to disabled dependency " >&5
+echo "$as_me: rfc4103 support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_RFC4103=no
+	    fi
+	  fi
+
+          if test "x" != "x"; then
+            if test "x$" != "xyes"; then
+              { echo "$as_me:$LINENO: rfc4103 support disabled due to disabled dependency " >&5
+echo "$as_me: rfc4103 support disabled due to disabled dependency " >&6;}
+	      OPAL_HAS_RFC4103=no
+	    fi
+	  fi
+
+
+          { echo "$as_me:$LINENO: checking whether to enable RFC4103 support" >&5
+echo $ECHO_N "checking whether to enable RFC4103 support... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $OPAL_HAS_RFC4103" >&5
+echo "${ECHO_T}$OPAL_HAS_RFC4103" >&6; }
+
+
+          if test "x$OPAL_HAS_RFC4103" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define OPAL_HAS_RFC4103 1
 _ACEOF
 
           fi
@@ -11376,7 +11470,9 @@ OPAL_H323!$OPAL_H323$ac_delim
 OPAL_IAX2!$OPAL_IAX2$ac_delim
 OPAL_H224FECC!$OPAL_H224FECC$ac_delim
 OPAL_T38_CAPABILITY!$OPAL_T38_CAPABILITY$ac_delim
-OPAL_IM_CAPABILITY!$OPAL_IM_CAPABILITY$ac_delim
+OPAL_HAS_MSRP!$OPAL_HAS_MSRP$ac_delim
+OPAL_HAS_SIPIM!$OPAL_HAS_SIPIM$ac_delim
+OPAL_HAS_RFC4103!$OPAL_HAS_RFC4103$ac_delim
 OPAL_FAX!$OPAL_FAX$ac_delim
 OPAL_H450!$OPAL_H450$ac_delim
 OPAL_H460!$OPAL_H460$ac_delim
@@ -11408,7 +11504,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 57; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
