Added abort of configure if compulsory options in PTLib are disabled.
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/opal/trunk@22309 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -702,6 +702,7 @@ LIBDIR
 PTLIBDIR
 PTLIB_CFLAGS
 PTLIB_LIBS
+
 OPAL_PTLIB_SSL
 OPAL_PTLIB_ASN
 OPAL_PTLIB_EXPAT
@@ -5491,6 +5492,91 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
                           #include <ptbuildopts.h>
                           #include <ptlib.h>
+                          #include <ptclib/url.h>
+
+                          int main()
+                          {
+                            PURL url;
+                          }
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  opal_ptlib_option=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	opal_ptlib_option=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+          CXXFLAGS="$old_CXXFLAGS"
+          LDFLAGS="$old_LDFLAGS"
+
+
+          { echo "$as_me:$LINENO: checking PTLIB has URL" >&5
+echo $ECHO_N "checking PTLIB has URL... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
+echo "${ECHO_T}$opal_ptlib_option" >&6; }
+
+          if test "x" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    ="$opal_ptlib_option"
+
+	    if test "x$opal_ptlib_option" = "xyes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define  1
+_ACEOF
+
+	    fi
+          fi
+
+
+
+          old_CXXFLAGS="$CXXFLAGS"
+          old_LDFLAGS="$LDFLAGS"
+
+          CXXFLAGS="$CXXFLAGS $PTLIB_CFLAGS $PTLIB_CXXFLAGS"
+          if test "x${DEBUG_BUILD}" = xyes; then
+            LDFLAGS="$LDFLAGS $DEBUG_LIBS"
+          else
+            LDFLAGS="$LDFLAGS $RELEASE_LIBS"
+          fi
+
+          ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+          cat >conftest.$ac_ext <<_ACEOF
+
+                          #include <ptbuildopts.h>
+                          #include <ptlib.h>
                           #include <ptclib/pssl.h>
 
                           int main()
@@ -5537,15 +5623,22 @@ echo $ECHO_N "checking PTLIB has SSL... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_SSL="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_SSL" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_SSL="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_SSL 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -5616,15 +5709,22 @@ echo $ECHO_N "checking PTLIB has ASN.1... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_ASN="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_ASN" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_ASN="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_ASN 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -5695,15 +5795,22 @@ echo $ECHO_N "checking PTLIB has expat... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_EXPAT="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_EXPAT" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_EXPAT="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_EXPAT 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -5774,15 +5881,22 @@ echo $ECHO_N "checking PTLIB has video... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_VIDEO="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_VIDEO" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_VIDEO="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_VIDEO 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -5853,15 +5967,22 @@ echo $ECHO_N "checking PTLIB has wavfile... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_WAVFILE="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_WAVFILE" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_WAVFILE="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_WAVFILE 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -5932,15 +6053,22 @@ echo $ECHO_N "checking PTLIB has vxml... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_VXML="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_VXML" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_VXML="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_VXML 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6011,15 +6139,22 @@ echo $ECHO_N "checking PTLIB has ipv6... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_IPV6="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_IPV6" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_IPV6="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_IPV6 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6090,15 +6225,22 @@ echo $ECHO_N "checking PTLIB has dtmf... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_DTMF="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_DTMF" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_DTMF="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_DTMF 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6169,15 +6311,22 @@ echo $ECHO_N "checking PTLIB has ldap... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_LDAP="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_LDAP" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_LDAP="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_LDAP 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6248,15 +6397,22 @@ echo $ECHO_N "checking PTLIB has dns... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_DNS="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_DNS" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_DNS="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_DNS 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6327,15 +6483,22 @@ echo $ECHO_N "checking PTLIB has audio... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_AUDIO="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_AUDIO" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_AUDIO="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_AUDIO 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
@@ -6406,15 +6569,22 @@ echo $ECHO_N "checking PTLIB has config... $ECHO_C" >&6; }
           { echo "$as_me:$LINENO: result: $opal_ptlib_option" >&5
 echo "${ECHO_T}$opal_ptlib_option" >&6; }
 
-	  OPAL_PTLIB_CONFIG_FILE="$opal_ptlib_option"
+          if test "xOPAL_PTLIB_CONFIG_FILE" = "x" ; then
+	    if test "x$opal_ptlib_option" = "xno" ; then
+              echo "  ERROR: compulsory feature from PTLib disabled.";
+              exit 1;
+            fi
+          else
+	    OPAL_PTLIB_CONFIG_FILE="$opal_ptlib_option"
 
-	  if test "x$opal_ptlib_option" = "xyes" ; then
+	    if test "x$opal_ptlib_option" = "xyes" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define OPAL_PTLIB_CONFIG_FILE 1
 _ACEOF
 
-	  fi
+	    fi
+          fi
 
 
 
