Made error more .. forceful .. if pkg-config not installed on system.
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/opal/trunk@21607 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1967,6 +1967,12 @@ echo "${ECHO_T}no" >&6; }
 	fi
 
 fi
+if test -z "$PKG_CONFIG" ; then
+  { { echo "$as_me:$LINENO: error: OPAL must have pkg-config installed" >&5
+echo "$as_me: error: OPAL must have pkg-config installed" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 
 
