Add test for existence of aclocal.m4
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/opal/trunk@20070 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -663,6 +663,7 @@ ac_ct_CC
 CPP
 GREP
 EGREP
+PKG_CONFIG
 INSTALLPREFIX
 LIBDIR
 build
@@ -694,6 +695,8 @@ PLUGIN_CFLAGS
 HAS_FFMPEG
 FFMPEG_SOURCE
 FFMPEG_CFLAGS
+x264_CFLAGS
+x264_LIBS
 HAS_X264
 X264_CFLAGS
 X264_LIBS
@@ -716,7 +719,10 @@ CPPFLAGS
 CCC
 CC
 CFLAGS
-CPP'
+CPP
+PKG_CONFIG
+x264_CFLAGS
+x264_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1321,6 +1327,9 @@ Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
   CPP         C preprocessor
+  PKG_CONFIG  path to pkg-config utility
+  x264_CFLAGS C compiler flags for x264, overriding pkg-config
+  x264_LIBS   linker flags for x264, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -3596,7 +3605,126 @@ _ACEOF
 fi
 
 
-PKG_PROG_PKG_CONFIG()
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
 
 if test "x$prefix" = "xNONE"; then
    INSTALLPREFIX="/usr/local"
@@ -3605,6 +3733,11 @@ else
 fi
 
 
+
+if test \! -e ./aclocal.m4 ; then
+  echo "ERROR: you must run 'aclocal' before 'autoconf'"
+  exit
+fi
 
 
 LIBDIR="${libdir}"
@@ -7235,12 +7368,77 @@ if test "x$enable_x264" = "xstatic"; then
   have_x264_48="no"
   saved_LIBS="$LIBS"
 
-  echo ""
-  echo "--- WARNING: the call to PKG_CHECK_MODULES has been commented out due to compatibility problems"
-  echo "             with non-bleeding-edge systems. If you know how to fix this, please do!"
-  echo "             Until this happens, x264 probably won't work"
-  echo ""
-  #PKG_CHECK_MODULES([x264], [x264 >= 0.48], [ have_x264_48="yes" ], [  have_x264_48="no" ])
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for x264" >&5
+echo $ECHO_N "checking for x264... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$x264_CFLAGS"; then
+        pkg_cv_x264_CFLAGS="$x264_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x264 >= 0.48\"") >&5
+  ($PKG_CONFIG --exists --print-errors "x264 >= 0.48") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_x264_CFLAGS=`$PKG_CONFIG --cflags "x264 >= 0.48" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$x264_LIBS"; then
+        pkg_cv_x264_LIBS="$x264_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x264 >= 0.48\"") >&5
+  ($PKG_CONFIG --exists --print-errors "x264 >= 0.48") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_x264_LIBS=`$PKG_CONFIG --libs "x264 >= 0.48" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        x264_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x264 >= 0.48"`
+        else
+	        x264_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x264 >= 0.48"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$x264_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                  have_x264_48="no"
+elif test $pkg_failed = untried; then
+	  have_x264_48="no"
+else
+	x264_CFLAGS=$pkg_cv_x264_CFLAGS
+	x264_LIBS=$pkg_cv_x264_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	 have_x264_48="yes"
+fi
 
     if test $have_x264_48 = "no"; then
 
@@ -8779,6 +8977,7 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
 INSTALLPREFIX!$INSTALLPREFIX$ac_delim
 LIBDIR!$LIBDIR$ac_delim
 build!$build$ac_delim
@@ -8810,6 +9009,8 @@ PLUGIN_CFLAGS!$PLUGIN_CFLAGS$ac_delim
 HAS_FFMPEG!$HAS_FFMPEG$ac_delim
 FFMPEG_SOURCE!$FFMPEG_SOURCE$ac_delim
 FFMPEG_CFLAGS!$FFMPEG_CFLAGS$ac_delim
+x264_CFLAGS!$x264_CFLAGS$ac_delim
+x264_LIBS!$x264_LIBS$ac_delim
 HAS_X264!$HAS_X264$ac_delim
 X264_CFLAGS!$X264_CFLAGS$ac_delim
 X264_LIBS!$X264_LIBS$ac_delim
@@ -8822,7 +9023,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 91; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -9846,6 +10047,7 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
 INSTALLPREFIX!$INSTALLPREFIX$ac_delim
 LIBDIR!$LIBDIR$ac_delim
 build!$build$ac_delim
@@ -9877,6 +10079,8 @@ PLUGIN_CFLAGS!$PLUGIN_CFLAGS$ac_delim
 HAS_FFMPEG!$HAS_FFMPEG$ac_delim
 FFMPEG_SOURCE!$FFMPEG_SOURCE$ac_delim
 FFMPEG_CFLAGS!$FFMPEG_CFLAGS$ac_delim
+x264_CFLAGS!$x264_CFLAGS$ac_delim
+x264_LIBS!$x264_LIBS$ac_delim
 HAS_X264!$HAS_X264$ac_delim
 X264_CFLAGS!$X264_CFLAGS$ac_delim
 X264_LIBS!$X264_LIBS$ac_delim
@@ -9889,7 +10093,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 91; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
