Implementation of plugin for the CELT ultra-wideband codec Thanks to Stefan Knoblich

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -717,6 +717,9 @@ HAVE_X264
 THEORA_CFLAGS
 THEORA_LIBS
 HAVE_THEORA
+CELT_CFLAGS
+CELT_LIBS
+HAVE_CELT
 HAVE_LIBDL
 DL_LIBS
 HAVE_H264
@@ -748,7 +751,9 @@ LIBAVCODEC_LIBS
 X264_CFLAGS
 X264_LIBS
 THEORA_CFLAGS
-THEORA_LIBS'
+THEORA_LIBS
+CELT_CFLAGS
+CELT_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1376,6 +1381,8 @@ Some influential environment variables:
   THEORA_CFLAGS
               C compiler flags for THEORA, overriding pkg-config
   THEORA_LIBS linker flags for THEORA, overriding pkg-config
+  CELT_CFLAGS C compiler flags for CELT, overriding pkg-config
+  CELT_LIBS   linker flags for CELT, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6929,6 +6936,7 @@ HAVE_CAPI=yes
 HAVE_IXJ=no
 HAVE_H263=yes
 HAVE_H264=yes
+HAVE_CELT=no
 HAVE_SPANDSP=yes
 DEFAULT_TO_FULL_CAPABILITIES=yes
 X264_LINK_STATIC=no
@@ -9226,8 +9234,9 @@ fi
 
   if test "$has_samplerate" = "yes" ; then
     HAVE_SBC=yes
-    cat >>confdefs.h <<\_ACEOF
-#define HAVE_SBC yes
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SBC 1
 _ACEOF
 
     { echo "$as_me:$LINENO: Enabling SBC codec" >&5
@@ -10074,6 +10083,92 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
                    HAVE_THEORA=yes
+
+fi
+
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for CELT" >&5
+echo $ECHO_N "checking for CELT... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$CELT_CFLAGS"; then
+        pkg_cv_CELT_CFLAGS="$CELT_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"celt\"") >&5
+  ($PKG_CONFIG --exists --print-errors "celt") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_CELT_CFLAGS=`$PKG_CONFIG --cflags "celt" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$CELT_LIBS"; then
+        pkg_cv_CELT_LIBS="$CELT_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"celt\"") >&5
+  ($PKG_CONFIG --exists --print-errors "celt") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_CELT_LIBS=`$PKG_CONFIG --libs "celt" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        CELT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "celt"`
+        else
+	        CELT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "celt"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$CELT_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+                   HAVE_CELT=no
+
+elif test $pkg_failed = untried; then
+
+                   HAVE_CELT=no
+
+else
+	CELT_CFLAGS=$pkg_cv_CELT_CFLAGS
+	CELT_LIBS=$pkg_cv_CELT_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CELT 1
+_ACEOF
+
+                   HAVE_CELT=yes
 
 fi
 
@@ -11314,6 +11409,10 @@ if test -d audio/SBC ; then
   ac_config_files="$ac_config_files audio/SBC/Makefile"
 
 fi
+if test -d audio/celt ; then
+  ac_config_files="$ac_config_files audio/celt/Makefile"
+
+fi
 if test -d video/H.261-vic ; then
   ac_config_files="$ac_config_files video/H.261-vic/Makefile"
 
@@ -11942,6 +12041,7 @@ do
     "audio/G726/Makefile") CONFIG_FILES="$CONFIG_FILES audio/G726/Makefile" ;;
     "audio/IMA_ADPCM/Makefile") CONFIG_FILES="$CONFIG_FILES audio/IMA_ADPCM/Makefile" ;;
     "audio/SBC/Makefile") CONFIG_FILES="$CONFIG_FILES audio/SBC/Makefile" ;;
+    "audio/celt/Makefile") CONFIG_FILES="$CONFIG_FILES audio/celt/Makefile" ;;
     "video/H.261-vic/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.261-vic/Makefile" ;;
     "video/H.263-ffmpeg/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-ffmpeg/Makefile" ;;
     "video/H.263-1998/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-1998/Makefile" ;;
@@ -12160,6 +12260,9 @@ HAVE_X264!$HAVE_X264$ac_delim
 THEORA_CFLAGS!$THEORA_CFLAGS$ac_delim
 THEORA_LIBS!$THEORA_LIBS$ac_delim
 HAVE_THEORA!$HAVE_THEORA$ac_delim
+CELT_CFLAGS!$CELT_CFLAGS$ac_delim
+CELT_LIBS!$CELT_LIBS$ac_delim
+HAVE_CELT!$HAVE_CELT$ac_delim
 HAVE_LIBDL!$HAVE_LIBDL$ac_delim
 DL_LIBS!$DL_LIBS$ac_delim
 HAVE_H264!$HAVE_H264$ac_delim
@@ -12172,7 +12275,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -13067,6 +13170,7 @@ do
     "audio/G726/Makefile") CONFIG_FILES="$CONFIG_FILES audio/G726/Makefile" ;;
     "audio/IMA_ADPCM/Makefile") CONFIG_FILES="$CONFIG_FILES audio/IMA_ADPCM/Makefile" ;;
     "audio/SBC/Makefile") CONFIG_FILES="$CONFIG_FILES audio/SBC/Makefile" ;;
+    "audio/celt/Makefile") CONFIG_FILES="$CONFIG_FILES audio/celt/Makefile" ;;
     "video/H.261-vic/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.261-vic/Makefile" ;;
     "video/H.263-ffmpeg/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-ffmpeg/Makefile" ;;
     "video/H.263-1998/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-1998/Makefile" ;;
@@ -13287,6 +13391,9 @@ HAVE_X264!$HAVE_X264$ac_delim
 THEORA_CFLAGS!$THEORA_CFLAGS$ac_delim
 THEORA_LIBS!$THEORA_LIBS$ac_delim
 HAVE_THEORA!$HAVE_THEORA$ac_delim
+CELT_CFLAGS!$CELT_CFLAGS$ac_delim
+CELT_LIBS!$CELT_LIBS$ac_delim
+HAVE_CELT!$HAVE_CELT$ac_delim
 HAVE_LIBDL!$HAVE_LIBDL$ac_delim
 DL_LIBS!$DL_LIBS$ac_delim
 HAVE_H264!$HAVE_H264$ac_delim
@@ -13299,7 +13406,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -13780,6 +13887,7 @@ fi
 else
 echo "                    MPEG4 Part 2  :  no"
 fi
+echo "                            CELT  :  ${HAVE_CELT}"
 
 echo ""
 echo "                     SpanDSP FAX  :  $HAVE_SPANDSP"
