More FreeBSD compilation fixes thanks to Matthias Apitz <guru Sisis de>. Thanks !

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -5904,7 +5904,7 @@ echo $ECHO_N "checking system Speex version... $ECHO_C" >&6; }
       printf("%s\n", header.speex_version);
     }
 C_FILE
-    cc -o t t.c -lspeex > /dev/null 2>&1
+    cc -o t t.c $LDFLAGS -lspeex > /dev/null 2>&1
     if test \! -x t ; then
       { echo "$as_me:$LINENO: result: cannot determine - using library version" >&5
 echo "${ECHO_T}cannot determine - using library version" >&6; }
@@ -6565,7 +6565,76 @@ echo "${ECHO_T}no" >&6; }
   else
     { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-    { echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
+    if test `uname -s` = FreeBSD; then
+        { echo "$as_me:$LINENO: checking for dlopen in -lc" >&5
+echo $ECHO_N "checking for dlopen in -lc... $ECHO_C" >&6; }
+if test "${ac_cv_lib_c_dlopen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char dlopen ();
+int
+main ()
+{
+return dlopen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_c_dlopen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_c_dlopen=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_c_dlopen" >&5
+echo "${ECHO_T}$ac_cv_lib_c_dlopen" >&6; }
+if test $ac_cv_lib_c_dlopen = yes; then
+  HAS_LIBDL=1
+else
+  HAS_LIBDL=0
+fi
+
+    else
+        { echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
 echo $ECHO_N "checking for dlopen in -ldl... $ECHO_C" >&6; }
 if test "${ac_cv_lib_dl_dlopen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -6632,6 +6701,7 @@ else
   HAS_LIBDL=0
 fi
 
+    fi
   fi
 fi
 
@@ -7225,7 +7295,11 @@ done
 
         if test "x${x264_headers}" = "xtrue"; then
           if test "x$HAS_LIBDL" != "x0" ; then
-	    X264_LIBS="-ldl"
+            if test `uname -s` = FreeBSD; then
+	      X264_LIBS="-lc"
+            else
+	      X264_LIBS="-ldl"
+            fi
           fi
 
           { echo "$as_me:$LINENO: checking for x264 version >= 48" >&5
