Improved build system thanks to Mr M.
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/opal/trunk@20687 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -1319,6 +1319,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-debug          Enable debug build
   --enable-localgsm       Force use local version of GSM library rather than
                           system version
   --enable-localspeex     Force use local version of Speex library rather than
@@ -1340,7 +1341,6 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-debug            full, symbols or none (default: symbols)
   --with-libavcodec-source-dir
                           Directory with libavcodec source code, for MPEG4
                           rate control correction
@@ -1960,42 +1960,48 @@ fi
 
 
 
-# Check whether --with-with-debug was given.
-if test "${with_with_debug+set}" = set; then
-  withval=$with_with_debug;
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+          # Check whether --enable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval=$enable_debug; DEBUG_BUILD=$enableval
+else
+  DEBUG_BUILD=no
 fi
 
 
-          if test "x$with_debug" = xfull; then
-            CFLAGS="$CFLAGS -g -O0"
-            CXXFLAGS="$CXXFLAGS -g -O0"
-
-          { echo "$as_me:$LINENO: checking debugging support" >&5
-echo $ECHO_N "checking debugging support... $ECHO_C" >&6; }
-          { echo "$as_me:$LINENO: result: full" >&5
-echo "${ECHO_T}full" >&6; }
-
+          if test "x${DEBUG_BUILD}" = xyes; then
+            DEBUG_CFLAGS="-g3 -ggdb -O0 -D_DEBUG"
           else
-            if test "x$with_debug" = xnone; then
-              CFLAGS="$CFLAGS -O2"
-              CXXFLAGS="$CXXFLAGS -O2"
-
-          { echo "$as_me:$LINENO: checking debugging support" >&5
-echo $ECHO_N "checking debugging support... $ECHO_C" >&6; }
-          { echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6; }
-
-            else
-              CFLAGS="$CFLAGS -g -O2"
-              CXXFLAGS="$CXXFLAGS -g -O2"
-
-          { echo "$as_me:$LINENO: checking debugging support" >&5
-echo $ECHO_N "checking debugging support... $ECHO_C" >&6; }
-          { echo "$as_me:$LINENO: result: symbols" >&5
-echo "${ECHO_T}symbols" >&6; }
-
-            fi
+            DEBUG_CFLAGS="-g -O2"
           fi
+
+          { echo "$as_me:$LINENO: checking Debugging support" >&5
+echo $ECHO_N "checking Debugging support... $ECHO_C" >&6; }
+          { echo "$as_me:$LINENO: result: $DEBUG_BUILD" >&5
+echo "${ECHO_T}$DEBUG_BUILD" >&6; }
+
+
+CFLAGS="$CFLAGS $DEBUG_CFLAGS"
+CXXFLAGS="$CXXFLAGS $DEBUG_CFLAGS"
 
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -8657,12 +8663,15 @@ fi
 echo $ECHO_N "checking internal Speex version... $ECHO_C" >&6; }
           SPEEX_CFLAGS=
           SPEEX_LIBS=
-          if test -f "audio/Speex/libspeex/misc.h"
-          then
+          if test -f "audio/Speex/libspeex/misc.h"; then
             SPEEX_INTERNAL_VERSION=`grep "#define SPEEX_VERSION" audio/Speex/libspeex/misc.h | sed -e 's/^.*speex\-//' -e 's/\".*//'`
-    	  else
-            SPEEX_INTERNAL_VERSION=`grep "#define SPEEX_VERSION" plugins/audio/Speex/libspeex/misc.h | sed -e 's/^.*speex\-//' -e 's/\".*//'`
-    	  fi
+    	  elif test -f "src/codec/speex/libspeex/misc.h"; then
+            SPEEX_INTERNAL_VERSION=`grep "#define SPEEX_VERSION" src/codec/speex/libspeex/misc.h | sed -e 's/^.*speex\-//' -e 's/\".*//'`
+      	  else
+      	    { { echo "$as_me:$LINENO: error: Could not find internal speex library" >&5
+echo "$as_me: error: Could not find internal speex library" >&2;}
+   { (exit 1); exit 1; }; }
+      	  fi
           { echo "$as_me:$LINENO: result: $SPEEX_INTERNAL_VERSION" >&5
 echo "${ECHO_T}$SPEEX_INTERNAL_VERSION" >&6; }
 
@@ -9813,6 +9822,12 @@ done
           if test "$opal_dlfcn" = yes ; then
             { echo "$as_me:$LINENO: checking if dlopen is available" >&5
 echo $ECHO_N "checking if dlopen is available... $ECHO_C" >&6; }
+            ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
             cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -9860,7 +9875,8 @@ echo "${ECHO_T}no" >&6; }
             else
               { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-              if test `uname -s` = FreeBSD; then
+              case "$target_os" in
+                freebsd*|openbsd*|netbsd*|darwin*)
                   { echo "$as_me:$LINENO: checking for dlopen in -lc" >&5
 echo $ECHO_N "checking for dlopen in -lc... $ECHO_C" >&6; }
 if test "${ac_cv_lib_c_dlopen+set}" = set; then
@@ -9931,7 +9947,8 @@ else
   opal_libdl=no
 fi
 
-              else
+                ;;
+                *)
                   { echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
 echo $ECHO_N "checking for dlopen in -ldl... $ECHO_C" >&6; }
 if test "${ac_cv_lib_dl_dlopen+set}" = set; then
@@ -10002,7 +10019,8 @@ else
   opal_libdl=no
 fi
 
-              fi
+                ;;
+               esac
             fi
           fi
           if test $opal_libdl = yes; then
