Add initial version of SBC plugin codec Thanks to Christian Hoene

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -699,6 +699,7 @@ SIZE32
 SPEEX_CFLAGS
 SPEEX_LIBS
 SPEEX_SYSTEM
+HAVE_SBC
 HAVE_H263
 DEFAULT_TO_FULL_CAPABILITIES
 LIBAVCODEC_CFLAGS
@@ -1326,6 +1327,7 @@ Optional Features:
                           system version
   --enable-localspeex     Force use local version of Speex library rather than
                           system version
+  --enable-sbc            enable use of Bluetooth SBC for CD quality telephony
   --enable-ffmpeg-h263    enable plugin supporting H.263 via patched FFMPEG
   --enable-default-to-full-capabilties
                           default to full capabilities at empty fmtp lines
@@ -9146,6 +9148,95 @@ echo "${ECHO_T}using system Speex version $SPEEX_SYSTEM_VERSION" >&6; }
 
 
 
+# Check whether --enable-sbc was given.
+if test "${enable_sbc+set}" = set; then
+  enableval=$enable_sbc; has_sbc=$enableval
+else
+  has_sbc=
+fi
+
+
+if test "$has_sbc" = "yes" ; then
+  { echo "$as_me:$LINENO: checking for src_get_version in -lsamplerate" >&5
+echo $ECHO_N "checking for src_get_version in -lsamplerate... $ECHO_C" >&6; }
+if test "${ac_cv_lib_samplerate_src_get_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsamplerate  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char src_get_version ();
+int
+main ()
+{
+return src_get_version ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_samplerate_src_get_version=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_samplerate_src_get_version=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_samplerate_src_get_version" >&5
+echo "${ECHO_T}$ac_cv_lib_samplerate_src_get_version" >&6; }
+if test $ac_cv_lib_samplerate_src_get_version = yes; then
+  has_samplerate=yes
+else
+  has_samplerate=no
+fi
+
+  if test "$has_samplerate" = "yes" ; then
+    HAVE_SBC=yes
+    cat >>confdefs.h <<\_ACEOF
+#define HAVE_SBC yes
+_ACEOF
+
+    { echo "$as_me:$LINENO: Enabling SBC codec" >&5
+echo "$as_me: Enabling SBC codec" >&6;}
+  fi
+fi
+
+
+
 
           if test "x$HAVE_H263" = "x"; then
             { { echo "$as_me:$LINENO: error: No default specified for HAVE_H263, please correct configure.ac" >&5
@@ -11219,6 +11310,10 @@ if test -d audio/IMA_ADPCM ; then
   ac_config_files="$ac_config_files audio/IMA_ADPCM/Makefile"
 
 fi
+if test -d audio/SBC ; then
+  ac_config_files="$ac_config_files audio/SBC/Makefile"
+
+fi
 if test -d video/H.261-vic ; then
   ac_config_files="$ac_config_files video/H.261-vic/Makefile"
 
@@ -11846,6 +11941,7 @@ do
     "audio/LPC_10/Makefile") CONFIG_FILES="$CONFIG_FILES audio/LPC_10/Makefile" ;;
     "audio/G726/Makefile") CONFIG_FILES="$CONFIG_FILES audio/G726/Makefile" ;;
     "audio/IMA_ADPCM/Makefile") CONFIG_FILES="$CONFIG_FILES audio/IMA_ADPCM/Makefile" ;;
+    "audio/SBC/Makefile") CONFIG_FILES="$CONFIG_FILES audio/SBC/Makefile" ;;
     "video/H.261-vic/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.261-vic/Makefile" ;;
     "video/H.263-ffmpeg/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-ffmpeg/Makefile" ;;
     "video/H.263-1998/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-1998/Makefile" ;;
@@ -12005,6 +12101,7 @@ SIZE32!$SIZE32$ac_delim
 SPEEX_CFLAGS!$SPEEX_CFLAGS$ac_delim
 SPEEX_LIBS!$SPEEX_LIBS$ac_delim
 SPEEX_SYSTEM!$SPEEX_SYSTEM$ac_delim
+HAVE_SBC!$HAVE_SBC$ac_delim
 HAVE_H263!$HAVE_H263$ac_delim
 DEFAULT_TO_FULL_CAPABILITIES!$DEFAULT_TO_FULL_CAPABILITIES$ac_delim
 LIBAVCODEC_CFLAGS!$LIBAVCODEC_CFLAGS$ac_delim
@@ -12015,7 +12112,6 @@ LIBAVCODEC_LIB_NAME!$LIBAVCODEC_LIB_NAME$ac_delim
 HAVE_LIBAVCODEC!$HAVE_LIBAVCODEC$ac_delim
 LIBAVCODEC_SOURCE_DIR!$LIBAVCODEC_SOURCE_DIR$ac_delim
 X264_CFLAGS!$X264_CFLAGS$ac_delim
-X264_LIBS!$X264_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -12057,6 +12153,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+X264_LIBS!$X264_LIBS$ac_delim
 X264_LIB_NAME!$X264_LIB_NAME$ac_delim
 X264_LINK_STATIC!$X264_LINK_STATIC$ac_delim
 HAVE_X264!$HAVE_X264$ac_delim
@@ -12075,7 +12172,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -12969,6 +13066,7 @@ do
     "audio/LPC_10/Makefile") CONFIG_FILES="$CONFIG_FILES audio/LPC_10/Makefile" ;;
     "audio/G726/Makefile") CONFIG_FILES="$CONFIG_FILES audio/G726/Makefile" ;;
     "audio/IMA_ADPCM/Makefile") CONFIG_FILES="$CONFIG_FILES audio/IMA_ADPCM/Makefile" ;;
+    "audio/SBC/Makefile") CONFIG_FILES="$CONFIG_FILES audio/SBC/Makefile" ;;
     "video/H.261-vic/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.261-vic/Makefile" ;;
     "video/H.263-ffmpeg/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-ffmpeg/Makefile" ;;
     "video/H.263-1998/Makefile") CONFIG_FILES="$CONFIG_FILES video/H.263-1998/Makefile" ;;
@@ -13130,6 +13228,7 @@ SIZE32!$SIZE32$ac_delim
 SPEEX_CFLAGS!$SPEEX_CFLAGS$ac_delim
 SPEEX_LIBS!$SPEEX_LIBS$ac_delim
 SPEEX_SYSTEM!$SPEEX_SYSTEM$ac_delim
+HAVE_SBC!$HAVE_SBC$ac_delim
 HAVE_H263!$HAVE_H263$ac_delim
 DEFAULT_TO_FULL_CAPABILITIES!$DEFAULT_TO_FULL_CAPABILITIES$ac_delim
 LIBAVCODEC_CFLAGS!$LIBAVCODEC_CFLAGS$ac_delim
@@ -13140,7 +13239,6 @@ LIBAVCODEC_LIB_NAME!$LIBAVCODEC_LIB_NAME$ac_delim
 HAVE_LIBAVCODEC!$HAVE_LIBAVCODEC$ac_delim
 LIBAVCODEC_SOURCE_DIR!$LIBAVCODEC_SOURCE_DIR$ac_delim
 X264_CFLAGS!$X264_CFLAGS$ac_delim
-X264_LIBS!$X264_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -13182,6 +13280,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+X264_LIBS!$X264_LIBS$ac_delim
 X264_LIB_NAME!$X264_LIB_NAME$ac_delim
 X264_LINK_STATIC!$X264_LINK_STATIC$ac_delim
 HAVE_X264!$HAVE_X264$ac_delim
@@ -13200,7 +13299,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -13657,6 +13756,12 @@ fi
 echo "                            LPC10 :  yes"
 echo "                            G.726 :  yes"
 echo "                        IMA_ADPCM :  yes"
+
+if test "x${HAVE_SBC}" = "xyes" ; then
+echo "                              SBC :  yes"
+else
+echo "                              SBC :  no"
+fi
 
 echo ""
 
