Find ffmpeg include even if its located in some strange ffmpeg/libavcodec path
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/opal/trunk@20374 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -3949,7 +3949,6 @@ STDCCFLAGS=${STDCCFLAGS}
 
 
 
-
 H323_GSMAMR_NB_FLOAT=0
 if test -r "./audio/gsm-amr/src/interf_dec.h" ; then
   { echo "$as_me:$LINENO: Enabling GSM-AMR plugin" >&5
@@ -6894,7 +6893,7 @@ _ACEOF
 
           fi
 
-
+                   LIBAVCODEC_HEADER=
           if test "${ac_cv_header_libavcodec_avcodec_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for libavcodec/avcodec.h" >&5
 echo $ECHO_N "checking for libavcodec/avcodec.h... $ECHO_C" >&6; }
@@ -7027,11 +7026,13 @@ cat >>confdefs.h <<\_ACEOF
 #define LIBAVCODEC_HEADER "libavcodec/avcodec.h"
 _ACEOF
 
-                                     LIBAVCODEC_HEADER="libavcodec/avcodec.h"
+                           LIBAVCODEC_HEADER="libavcodec/avcodec.h"
 
-else
+fi
 
-                           if test "${ac_cv_header_ffmpeg_avcodec_h+set}" = set; then
+
+          if test x$LIBAVCODEC_HEADER = x; then
+            if test "${ac_cv_header_ffmpeg_avcodec_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for ffmpeg/avcodec.h" >&5
 echo $ECHO_N "checking for ffmpeg/avcodec.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_ffmpeg_avcodec_h+set}" = set; then
@@ -7163,21 +7164,156 @@ cat >>confdefs.h <<\_ACEOF
 #define LIBAVCODEC_HEADER "ffmpeg/avcodec.h"
 _ACEOF
 
-                                            LIBAVCODEC_HEADER="ffmpeg/avcodec.h"
+                             LIBAVCODEC_HEADER="ffmpeg/avcodec.h"
 
+fi
+
+
+          fi
+          if test x$LIBAVCODEC_HEADER = x; then
+            if test "${ac_cv_header_ffmpeg_libavcodec_avcodec_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for ffmpeg/libavcodec/avcodec.h" >&5
+echo $ECHO_N "checking for ffmpeg/libavcodec/avcodec.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_ffmpeg_libavcodec_avcodec_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_ffmpeg_libavcodec_avcodec_h" >&5
+echo "${ECHO_T}$ac_cv_header_ffmpeg_libavcodec_avcodec_h" >&6; }
 else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking ffmpeg/libavcodec/avcodec.h usability" >&5
+echo $ECHO_N "checking ffmpeg/libavcodec/avcodec.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <ffmpeg/libavcodec/avcodec.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
-                                            { { echo "$as_me:$LINENO: error: Cannot find libavcodec header file" >&5
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking ffmpeg/libavcodec/avcodec.h presence" >&5
+echo $ECHO_N "checking ffmpeg/libavcodec/avcodec.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ffmpeg/libavcodec/avcodec.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ffmpeg/libavcodec/avcodec.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: ffmpeg/libavcodec/avcodec.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for ffmpeg/libavcodec/avcodec.h" >&5
+echo $ECHO_N "checking for ffmpeg/libavcodec/avcodec.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_ffmpeg_libavcodec_avcodec_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_ffmpeg_libavcodec_avcodec_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_ffmpeg_libavcodec_avcodec_h" >&5
+echo "${ECHO_T}$ac_cv_header_ffmpeg_libavcodec_avcodec_h" >&6; }
+
+fi
+if test $ac_cv_header_ffmpeg_libavcodec_avcodec_h = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define LIBAVCODEC_HEADER "ffmpeg/libavcodec/avcodec.h"
+_ACEOF
+
+                             LIBAVCODEC_HEADER="ffmpeg/libavcodec/avcodec.h"
+
+fi
+
+
+          fi
+          if test x$LIBAVCODEC_HEADER = x; then
+            { { echo "$as_me:$LINENO: error: Cannot find libavcodec header file" >&5
 echo "$as_me: error: Cannot find libavcodec header file" >&2;}
    { (exit 1); exit 1; }; }
-
-fi
-
-
-
-fi
-
-
+          fi
 
 
 fi
